### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#1]
**Land on App and choose what to do**

**Value Statement:** 
As a customer I want to be greeted and introduced to the App and see the options that are available to me.

**Description**
![Bildschirmfoto 2021-06-03 um 16 03 49](https://user-images.githubusercontent.com/82114506/120657953-4b6c1100-c485-11eb-8fa3-96dc8545bc18.png)

**Acceptance Criteria:**
- [x] User gets asked the question if he is ready to find a new friend
- [x] User can click on first button to be redirected to the search mask, where he can enter criteria for his animal search
- [x] User can click on second button to be redirected to the form mask, where he can enter a new animal into the database 

**Complexity:**
M

**Tasks:**
- [x] New feature branch 'landing-page'
- [x] Create and Add Logo
- [x] Add Question for user, if he is ready to find a new friend
- [x] Add Button which redirects to search mask
- [x] Add Button which redirects to form

**Comment by SabMueller** [comment]
**Storyname: Land on App and choose what to do**
**Value Statement:** 
As a customer I want to be greeted and introduced to the App and see the options that are available to me.
**Acceptance Criteria:**
-[] Click on the Logo to toggle animation
-[] User gets asked the question if he is ready to find a new friend
-[] User can click on first button to be redirected to the search mask, where he can enter criteria for his animal search
-[] User can click on second button to be redirected to the form mask, where he can enter a new animal into the database 
**Complexity:**
M
**Tasks:**
-[] New feature branch 'landing-page'
-[] Create and Add Logo
-[] Animate Logo on Click
-[] Add Question for user, if he is ready to find a new friend
-[] Add Button which redirects to search mask
-[] Add Button which redirects to form
-[] Add Styleguidist component for buttons
