### ISSUE TITLE
Show Infos / Profile Page for each Organisation / Animal Owner

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#10]
OPTIONAL
**Show Profile of Organizations with Info:**

**Value Statement:**
As a customer I want to get to know the organization that owns the animal so that I can make an informed decision about adopting the animal.

**Description:**
![Bildschirmfoto 2021-06-03 um 23 01 22](https://user-images.githubusercontent.com/82114506/120711404-a02c7d80-c4bf-11eb-9b0a-38355fabd585.png)

**Acceptance Criteria:**
- [ ] User can see Name of Organization and Picture of Organization 
- [ ] Optional: User can see Map / Location of the organization
- [ ] User can see description of organization
- [ ] User can click on navigation to navigate back to main screen, favorites or start a new search 

**Complexity:**
M

**Tasks:**
- [ ] Create new feature branch 'organization-info'
- [ ] Add header and headline
- [ ] Fetch Organization name, picture, location and description from database
- [ ] display info accordingly
- [ ] add navigation
