### ISSUE TITLE
Show Infos for Animal Breed

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#11]
OPTIONAL
**Show Infos of the Respective Breeds:**

**Value Statement:**
As a customer I want to get to know more about the animal's breed so that I can decide more easily if the animal breed suits my lifestyle.

**Description:**
![Bildschirmfoto 2021-06-03 um 23 31 22](https://user-images.githubusercontent.com/82114506/120714687-d10eb180-c4c3-11eb-9afd-bcc4f07844c9.png)

**Acceptance Criteria:**
- [ ] User can see Name and picture of breed
- [ ] User can see Characteristics of the breed
- [ ] User can see description of the breed
- [ ] User can click on navigation to navigate back to main screen, favorites or start a new search 

**Complexity:**
L

**Tasks:**
- [ ] New Feature Branch 'breed-info'
- [ ] Add header and headline
- [ ] Fetch breed name, picture, characteristics and description from database
- [ ] display info accordingly
- [ ] add navigation
