### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#14]
**Show and be able to use Navigation Bar:**

**Value Statement:**
As a customer I want to have a navigation bar, so that I can have a better overview and be able to switch pages quickly. 

**Description:**
Navigation bar that is only visible on certain pages and which Buttons / Links vary, depending on the current page the user is on.

**Acceptance Criteria:**
- [x] User can use navigation bar to navigate to a variety of pages, depending on their current page

**Tasks:**
- [ x ] Create feature branch 'navigation
- [x] Create Footer Navigation
- [x] Create Buttons or Icons and insert them
- [x] Add according links
- [x] Test their functionality
