### ISSUE TITLE
Add Animal for Adoption via Form

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#2]
**Add Animal For Adoption in a Form**

**Value Statement:**
As a customer / organization  I want to add animals to the database so that they can be found by other users and be adopted by them.

**Description:**
![Bildschirmfoto 2021-06-03 um 15 49 52](https://user-images.githubusercontent.com/82114506/120655828-59209700-c483-11eb-860e-3177778937c2.png)

**Acceptance Criteria:**
- [x] User can add Information about the animal through input in various fields or selections from dropdown menus 
- [x] User can upload a profile pic of the animal he/she wishes to add by clicking on the Upload Button
- [x] User can Submit the data by clicking on a button called Submit
- [x] User can go back to the landing page by clicking on a button called Go Back

**Complexity:**
XL

**Tasks:**
- [x] New feature branch 'animal-form'
- [x] Create input fields / dropdown menus for the various values (name, type, age, gender, breen, characteristics, description, organization, organization e-mail)
- [x] Create upload buttons that enable image uploads for animal profile pic and organization
- [x] Implement functionality / Connect frontend to backend
- [x] Create Submit button that sends entries to database
- [x] Create Go Back button that returns to landing page
