### ISSUE TITLE
Search for Animals to Adopt

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#4]
*Search for adoptable animals:**

**Value Statement:**
As a customer I want to search for animals / pets to adopt, in order to see which animals are available for adoption and find my perfect match.

**Description:**
![Bildschirmfoto 2021-06-03 um 16 19 04](https://user-images.githubusercontent.com/82114506/120660246-6ccdfc80-c487-11eb-81c6-1069fe2fd4bd.png)

**Acceptance Criteria:**
- [x] User can choose animal type / gender and organization from dropdown menus and can either select specific ones or 'all'.
- [x] User can click on Search and is redirected to the results page

**Complexity:**
L

**Tasks:**
- [x] New feature branch 'animal-search'
- [x] Add dropdown menus for animal types, gender and organization
- [x] Add Search button which redirects user to results page
- [x] Implement search logic
