### ISSUE TITLE
Main Page / Show Results for Search

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#5]
**Show Search Results and additional Content:**

**Value Statement:**
As a customer I want to see my search results, see additional infos for them and interact with them in order for me to find out more about the animals / pets and add them to my favorites

**Description:**
![Bildschirmfoto 2021-06-03 um 16 46 58](https://user-images.githubusercontent.com/82114506/120664567-52961d80-c48b-11eb-8c6d-1b71507f8c8a.png)

**Acceptance Criteria:**
- [x] User can see how many animals matched the criteria for his search
- [x] User can see big Profile Pictures of the Animals, with their respective names displayed on them
- [x] User can click on an icon at the image's top to add them to their favorites
- [x] User can click on an icon at the image's bottom to display additional infos
- [x] User can see the animal's breed and organization, as well as their respective characteristics and description
Optional: User can click on breed to be redirected to an info page
Optional: User can click on the organization's name to find out more about them
- [x] User can scroll through search results
- [x] User can use navigation bar to navigate to their Favorites or start a new Search 

**Complexity:**
XL

**Tasks:**
- [x] New feature branch 'animal-results'
- [x] Add how many entries matched the search criteria
- [x] Fetch Results from database and map over Results and display them as Cards with Names
- [x] Add Favorite-Icon and add toggle function to it
- [x] Add Icon which shows additional info, when clicked on 
- [x] Fetch Breed / Organization from Database and display them on info box
- [x] Fetch Characteristics and Description from Database and display them on info box
Optional: Redirect user to organization info page when clicked on 
Optional: Redirect user to breed info page when clicked on
