### ISSUE TITLE
Favorite Animals

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#6]
**Add Animal To Favorites and Display them on separate page**

**Value Statement:**
As a customer I want to mark animals as favorites in order to put them on a separate list and to consider them for adoption

**Description:**
![Bildschirmfoto 2021-06-03 um 19 20 46](https://user-images.githubusercontent.com/82114506/120686002-cf7fc200-c4a0-11eb-8519-dc2950b42c46.png)

**Acceptance Criteria:**
- [x] Click on Icon to add Animals to Favorites
- [x] Click on Icon again to remove them from favorites
- [x] Click on a button below the animal card in order to get in touch with organization that owns pet
- [x] Click on navigation buttons to either be redirected to search results or start over with a new search 

**Complexity:**
L

**Tasks:**
- [x] Create new branch 'favorites'
- [x] Create Header / Headline
- [x] Map over Favorited Animals to display them as cards
- [x] Add toggle function to favorite - icon 
- [x] Add button that redirects user to contact page
- [x] change navigation bar buttons and make sure they lead to the right pages
