### ISSUE TITLE
Get in touch with Organisation / Animal Owner

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#7]
**Get in Touch with Organisation / Animal Owner:**

**Value Statement:**
As a customer I would like to be able to get in touch with the organisation that owns the animal so that I can ask them questions and maybe schedule a date to meet the animal

**Description:**
![Bildschirmfoto 2021-06-03 um 19 35 41](https://user-images.githubusercontent.com/82114506/120688123-05be4100-c4a3-11eb-965c-5297e72681df.png)

**Acceptance Criteria:**
- [x] User can see Card of Selected Animal to double check if it's the right one
- [x] User can see which organization owns the animal
- [x] User can see contact information of organization

**Complexity:**
L

**Tasks:**
- [x] New feature branch 'contact'
- [x] Add header and headline
- [x] Add Animal Card
- [x] Add Name of Organization
