### ISSUE TITLE
Add backend structure / dummy content

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#8]
**Add backend structure to project and some dummy content**

**Value Statement:**
As a customer I want to be able to have search results so that I can actually use the app.

**Description:**
It is necessary to setup backend-structure, as well as MongoDB for the project to work. Dummy content will have to be inserted in order for the first users to have search results.

**Acceptance Criteria:**
- [x] User can actually enter data into database online.

**Complexity:**
M

**Tasks:**
- [x] New feature branch 'backend-structure'
- [x] write GET, POST, PUT, REMOVE functions
- [x] setup mongodb 
- [x] connect mongodb succesfully to server
