### ISSUE TITLE
Add Local Storage for Favorites

### ISSUE THREAD

**Issue by SabMueller** [SabMueller/capstone-project-pawzies#9]
**Add Local Storage to Favorites:**

**Value Statement:**
As a customer I would like to be able to store my favorites so that when I come back, I have my favorites ready for me and do not have to search for them again

**Description:**
Add Local Storage to Favorites to enhance user experience.

**Acceptance Criteria:**
- [x] User still keeps favorite animals when he/she leaves the page or refreshes it

**Complexity:**
M

**Tasks:**
- [x] New feature branch 'local-storage-favorites'
- [x] Add WriteTo and LoadFrom LocalStorage Functions
- [x] Connect them via useEffect to Favorites
- [x] Test usability
